######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 6 18:22:03 2008
######################################################################

TEMPLATE = app
CONFIG += qt console debug
QT -= gui
QT += network

TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

LIBS += -L../lib/core -lcore
INCLUDEPATH += ../lib/core

QMAKE_CXXFLAGS_DEBUG += -O0
QMAKE_LFLAGS_DEBUG += -g

# Input
SOURCES += main.cpp server.cpp
HEADERS += server.h
