######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 6 18:22:03 2008
######################################################################

TEMPLATE = app
CONFIG = qt
QT -= gui

TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

LIBS += -L../lib/core -lcore
INCLUDEPATH += ../lib/core

# Input
SOURCES += main.cpp
