######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 6 18:15:50 2008
######################################################################

TEMPLATE = app
CONFIG += debug
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

QMAKE_CXXFLAGS_DEBUG += -O0
QMAKE_LFLAGS_DEBUG += -g

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
FORMS += mainwindow.ui


TRANSLATIONS = gui_ru.ts
