######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 6 18:15:50 2008
######################################################################

TEMPLATE = lib
CONFIG = staticlib qt
QT -= gui
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += serial.h device.h
SOURCES += serial.cpp device.cpp
