######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 6 18:15:50 2008
######################################################################

TEMPLATE = lib
CONFIG = staticlib qt debug
QT -= gui
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QMAKE_CXXFLAGS_DEBUG += -O0
QMAKE_LFLAGS_DEBUG += -g

# Input
HEADERS += serial.h device.h
SOURCES += serial.cpp device.cpp
