######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 6 18:15:50 2008
######################################################################

TEMPLATE = lib
CONFIG = staticlib qt debug
QT -= gui
QT += sql
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QMAKE_CXXFLAGS_DEBUG += -O0
QMAKE_LFLAGS_DEBUG += -g

# Input
HEADERS += serial.h device.h shell.h database.h
SOURCES += serial.cpp device.cpp shell.cpp database.cpp
